version: '3'
services:
  api:
    build:
    ports: ["8080:8080"]
    depends_on: [redis, postgres]
  worker:
    build:
    command: ./worker
    depends_on: [redis, postgres]
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: task_db

